### ISSUE TITLE
赞助组志愿者要求

### ISSUE THREAD

**Issue by ivanightingale** [sosconf/sosconf-2019-frontend#27]
“- 运营和维护
赞助商及合作伙伴的良好关系！”
应为
“- 运营和维护赞助商及合作伙伴的良好关系！”
（同一行）

**Comment by import-yuefeng** [comment]
改动类型: 网页展现的文字

**Comment by ivanightingale** [comment]
改动类型: 网页展现的文字xxx
改动内容:
“运营和维护
赞助商及合作伙伴的良好关系！”
应为
“- 运营和维护赞助商及合作伙伴的良好关系！”
（从分两行改为同一行）
改动时效: 2天内(只是范例)
改动项目: sosconf-2019-frontend
改动影响范围: 中文版

**Comment by import-yuefeng** [comment]
> 改动类型: 网页展现的文字xxx
> 改动内容:
> “运营和维护
> 赞助商及合作伙伴的良好关系！”
> 应为
> “- 运营和维护赞助商及合作伙伴的良好关系！”
> （从分两行改为同一行）
> 改动时效: 2天内(只是范例)
> 改动项目: sosconf-2019-frontend
> 改动影响范围: 中文版

感谢配合~ 这样感觉会清楚好多呢~

**Comment by cuijinyu** [comment]
已经完成
