### ISSUE TITLE
更新About页面的英文版本

### ISSUE THREAD

**Issue by ivanightingale** [sosconf/sosconf-2019-frontend#49]
改动类型: 英文文本、按钮链接
改动内容: About页面的英文版本使用以下内容：
Student Open Source Conference(sosconf) 2019 is collaborated on by Opening Source Org and Society of Opening Source SC. Opening Source Org is an international community of enthusiasts who make great contributions to open source. SOSSC is a newborn student organization at USC. It is brought to students by students.  sosconf is the very first student-held, student-centered international conference focusing on open source. It will be a great opportunity for students around the world to gather, connect and learn from each other. For companies and organizations, it will be a chance to show their commitment to open source and to search for student talents. The conference will be held at University of Southern California in Los Angeles on September 1, with mini-events and talks focusing on different technology fields. Students of any education levels around the world are welcome to participate as audience, volunteers or speakers, with an opportunity of obtaining travel reimbursement.

Contact us的按钮链接请设为mailto:hi@sosconf.org （目前为没有链接）
改动时效: 周日前（05/19）
改动项目: sosconf-2019-frontend
改动影响范围: About页面

**Comment by ivanightingale** [comment]
现在网页上的文本只是上面文字的一部分，是因为排版限制吗？
另外，请修改一下contact us的链接（见改动内容的最后一行）

**Comment by ivanightingale** [comment]
@cuijinyu

**Comment by ivanightingale** [comment]
@cuijinyu 可否说明一下情况？

**Comment by cuijinyu** [comment]
这几天在家 没有来得及更新 另外要注明的是 现在的自动部署是以tag进行的

**Comment by ivanightingale** [comment]
@cuijinyu 那么英文about的改动可以进行吗？

**Comment by cuijinyu** [comment]
可以进行 现在呈现的就是最新的更新，然后的话tag是因为后端更换了k8s集群，短时间内只能用tag触发钩子
